// Criar Produto
POST http://localhost:4003/product
Content-Type: application/json

{
    "name": "iPhone",
    "bar_code": "sadafdfdasasaaawjdfkjdwkjndknassasfkças",
    "price": 1230
}

###
// Criar Categoria
POST http://localhost:4003/category
Content-Type: application/json

{
    "name": "mobile"
}


###
// Criar Categoria com Produto
POST http://localhost:4003/categoryProduct
Content-Type: application/json

{
    "id_product": "811adde2-d017-418d-aebc-01162f3a32ae",
    "id_category": "1b4e3577-b472-4187-926e-1c8a365b600c"
}

###
// Criar Produto com categoria existente
POST http://localhost:4003/productWithCategory
Content-Type: application/json

{
    "name": "Sansumg J10",
    "bar_code": "aassdaasasaaawjdfkjdwkjndknassasfkçasdafds",
    "price": 10232,
    "id_category": "1b4e3577-b472-4187-926e-1c8a365b600c"
}